"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { inputClass, buttonSecondaryClass } from "@/lib/ui/styles";
import { GSTN_PROVIDERS, GSTN_ENVIRONMENTS, type GstnProvider, type GstnEnvironment } from "@/lib/domain";

const PROVIDER_LABEL: Record<GstnProvider, string> = {
  cleartax: "ClearTax", cygnet: "Cygnet GSP", mastergst: "MasterGST", iris: "IRIS GSP", other: "Other",
};

export interface GstnConnectionState {
  provider: GstnProvider;
  environment: GstnEnvironment;
  gstin: string;
  status: "not_connected" | "pending" | "connected" | "error";
}

/**
 * Records intent, not a working connection — see
 * 20261001000008_gstn_connections.sql and lib/gstn/client.ts for why every
 * save here lands as "pending" rather than actually connecting to anything.
 */
export function GstnConnectionForm({
  current,
  orgGstin,
  isOwner,
}: {
  current: GstnConnectionState | null;
  /** Pre-fills GSTIN from the organisation's own tax_id — almost always the
   *  right value, still editable in case it differs. */
  orgGstin: string | null;
  isOwner: boolean;
}) {
  const router = useRouter();
  const [provider, setProvider] = useState<GstnProvider>(current?.provider ?? "cleartax");
  const [environment, setEnvironment] = useState<GstnEnvironment>(current?.environment ?? "sandbox");
  const [gstin, setGstin] = useState(current?.gstin ?? orgGstin ?? "");
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");

  async function save(e: React.FormEvent) {
    e.preventDefault();
    setSaving(true);
    setError("");
    const res = await fetch("/api/settings/gstn-connection", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ provider, environment, gstin }),
    });
    setSaving(false);
    if (!res.ok) {
      const body = await res.json().catch(() => ({}));
      setError(body.error ?? "Could not save this connection.");
      return;
    }
    router.refresh();
  }

  return (
    <div>
      <p className="mb-1.5 text-[13px] font-medium text-ink">GSTN e-invoice / e-way bill connection</p>
      <p className="mb-3 text-[12.5px] text-ink-3">
        Moonbook doesn&apos;t call any GST Suvidha Provider yet — this records which one you
        intend to connect through, so the moment that integration exists, nothing here has to
        be rebuilt. Until then, use the &quot;E-way bill &amp; e-invoice&quot; card on each
        document to record numbers you generated by hand.
      </p>

      {current && (
        <p className="mb-3 rounded-md bg-pending-tint px-3 py-2 text-[12.5px] text-pending-ink">
          {PROVIDER_LABEL[current.provider]} · {current.environment} · status: {current.status.replace("_", " ")}
        </p>
      )}

      {!isOwner ? (
        <p className="text-[13px] text-ink-3">Only an owner can change this.</p>
      ) : (
        <form onSubmit={save} className="grid gap-3 min-[560px]:grid-cols-3">
          <div>
            <label htmlFor="provider" className="mb-1.5 block text-[13px] font-medium text-ink">Provider</label>
            <select id="provider" value={provider} onChange={(e) => setProvider(e.target.value as GstnProvider)} className={inputClass}>
              {GSTN_PROVIDERS.map((p) => <option key={p} value={p}>{PROVIDER_LABEL[p]}</option>)}
            </select>
          </div>
          <div>
            <label htmlFor="environment" className="mb-1.5 block text-[13px] font-medium text-ink">Environment</label>
            <select id="environment" value={environment} onChange={(e) => setEnvironment(e.target.value as GstnEnvironment)} className={inputClass}>
              {GSTN_ENVIRONMENTS.map((e) => <option key={e} value={e}>{e}</option>)}
            </select>
          </div>
          <div>
            <label htmlFor="gstin" className="mb-1.5 block text-[13px] font-medium text-ink">GSTIN</label>
            <input id="gstin" value={gstin} onChange={(e) => setGstin(e.target.value.toUpperCase())} required className={`${inputClass} font-mono uppercase`} />
          </div>
          <div className="min-[560px]:col-span-3">
            <button type="submit" disabled={saving} className={buttonSecondaryClass}>
              {saving ? "Saving…" : "Save"}
            </button>
          </div>
          {error && <p className="min-[560px]:col-span-3 rounded-md bg-overdue-tint p-3 text-[13px] text-overdue">{error}</p>}
        </form>
      )}
    </div>
  );
}
