import { type NextRequest } from "next/server";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { requireOwner } from "@/lib/auth/verify";
import { parseBody } from "@/lib/api/validate";
import { apiErr, apiOk } from "@/lib/api/response";
import { rpcError } from "@/lib/api/errors";
import { EINVOICE_STATUSES } from "@/lib/domain";

export const runtime = "nodejs";

/**
 * Records what a business already generated by hand on the government
 * e-way bill and Invoice Registration Portal — see the migration's own
 * header for why this is recording, not generating. A full replace, same
 * reasoning as update_activity: a partial PATCH would need null to mean
 * "leave this field alone," which makes clearing one impossible.
 */
const schema = z.object({
  ewb_no: z.string().trim().regex(/^\d{12}$/, "must be exactly 12 digits").optional().nullable(),
  ewb_valid_until: z.iso.datetime({ local: true }).optional().nullable(),
  irn: z.string().trim().regex(/^[0-9a-fA-F]{64}$/, "must be 64 hex characters").optional().nullable(),
  irn_ack_no: z.string().trim().max(60).optional().nullable(),
  irn_ack_date: z.iso.date().optional().nullable(),
  qr_code_data: z.string().trim().max(4000).optional().nullable(),
  einvoice_status: z.enum(EINVOICE_STATUSES).default("not_applicable"),
});

export async function PATCH(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const auth = await requireOwner();
  if (!auth.ok) return apiErr(auth.error, auth.status);

  const { id } = await params;
  const parsed = await parseBody(req, schema);
  if (!parsed.ok) return apiErr(parsed.error, 422);
  const v = parsed.data;

  const supabase = await createClient();
  const { data, error } = await supabase
    .rpc("set_document_compliance_refs", {
      p_document_id: id,
      p_ewb_no: v.ewb_no ?? undefined,
      p_ewb_valid_until: v.ewb_valid_until ?? undefined,
      p_irn: v.irn ?? undefined,
      p_irn_ack_no: v.irn_ack_no ?? undefined,
      p_irn_ack_date: v.irn_ack_date ?? undefined,
      p_qr_code_data: v.qr_code_data ?? undefined,
      p_einvoice_status: v.einvoice_status,
    })
    .single();

  if (error) return rpcError("PATCH /api/documents/[id]/compliance", error, "Could not save these references");
  return apiOk(data);
}
