import type { DocumentSnapshot } from "@/lib/pdf/snapshot";

/** Every invoice template implements exactly this signature — the data and
 *  its computation (tax, amount-in-words, money formatting) are identical
 *  across templates; only the JSX and styling differ. */
export interface InvoiceTemplateProps {
  snapshot: DocumentSnapshot;
  logoDataUri?: string | null;
  /** Live, read at render time — never part of the frozen snapshot, since a
   *  payment recorded after issue must show up "on the go" without the
   *  document itself ever being rewritten. Omitted entirely (not zeroed)
   *  when nothing has been settled yet, so a fresh invoice prints exactly
   *  as before. */
  balance?: { settledMinor: number; balanceDueMinor: number } | null;
  /** Standing, org-level invoice customization — same "cosmetic, not a fact
   *  about the transaction" reasoning as the logo and the template choice
   *  itself, so it's read live rather than frozen into a document's own
   *  issued_snapshot. Omitted (not defaulted) when the caller hasn't loaded
   *  it, so every existing call site keeps behaving exactly as before. */
  invoiceOptions?: { showHsn: boolean; terms: string | null } | null;
  /** Entered by hand from the government portals, never generated by this
   *  app — see 20261001000007_document_compliance_refs.sql. Live, same
   *  reasoning as `balance`: recorded after issue, so frozen into the
   *  snapshot would mean it could never show up on a reprint. */
  compliance?: { ewbNo: string | null; irn: string | null; irnAckNo: string | null } | null;
}

export type InvoiceTemplateComponent = (props: InvoiceTemplateProps) => React.JSX.Element;

export const TITLES: Record<string, string> = {
  invoice: "Tax Invoice",
  bill: "Purchase Bill",
  credit_note: "Credit Note",
  debit_note: "Debit Note",
};

/** ISO date → the organisation's locale. Parsed as UTC so a date-only value
 *  cannot shift a day in a timezone behind Greenwich. */
export function formatDate(iso: string, locale: string): string {
  const d = new Date(`${iso}T00:00:00Z`);
  if (Number.isNaN(d.getTime())) return iso;
  return new Intl.DateTimeFormat(locale, {
    day: "2-digit",
    month: "short",
    year: "numeric",
    timeZone: "UTC",
  }).format(d);
}

/** 2400.00 → "2400"; 2.5 → "2.5". */
export function trimNumber(n: number): string {
  return Number.isInteger(n) ? String(n) : String(Number(n.toFixed(2)));
}

/**
 * A 64-character IRN has no natural break point, and react-pdf's Yoga layout
 * only wraps at whitespace — inside a fixed-width column it silently clips
 * the overflow instead, which is how a printed compliance number ends up
 * missing its last two characters. Grouping into 4-character chunks (the
 * same convention GSTN's own IRN display uses) gives Yoga somewhere to
 * break, and reads more easily than one unbroken string besides.
 */
export function formatIrnForPrint(irn: string): string {
  return irn.match(/.{1,4}/g)?.join(" ") ?? irn;
}
